spring.application.name=equisibe-backend
spring.datasource.url=jdbc:mysql://localhost:3306/equisibe
spring.datasource.username=equisibe
spring.datasource.password=equisibe

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true